version: '3.3'

services:
  drupal:
    image: drupal:latest
    ports:
      - 8000:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: changeme
    command: [ "postgres", "-c", "wal_level=logical" ]
    volumes:
        - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  db_data:
