#!/bin/bash
#
# Simple start script
#
PLUMBER_RELAY_TYPE=cdc-postgres \
PLUMBER_RELAY_CDCPOSTGRES_HOSTNAME=localhost \
PLUMBER_RELAY_CDCPOSTGRES_USERNAME=postgres \
PLUMBER_RELAY_CDCPOSTGRES_PASSWORD=changeme \
PLUMBER_RELAY_CDCPOSTGRES_DATABASE=postgres \
PLUMBER_RELAY_CDCPOSTGRES_SLOT=plumber_slot \
PLUMBER_RELAY_CDCPOSTGRES_PUBLISHER=batchsh_plumber \
PLUMBER_RELAY_TOKEN=48fd9edd-eba3-4f07-8043-73b29357f63f \
plumber relay
